### ISSUE TITLE
Syncronous Interrupt hanging

### ISSUE THREAD

**Issue by jhaubrich** [golemparts/rppal#104]
I'm interacting with an ADC that has a busy signal while it does conversion. I block while the busy pin is high:

``` rust
let mut busy = Gpio::new()?.get(GPIO_BUSY)?.into_input_pullup();

loop {
    start_conversion();
    while busy.is_high() { /* block while we wait for conversion to finish */}
    ...
    read_data();
}
```

This gets me the basic functionality, but I wanted to use an interrupt on that pin instead. I set it up like so:

``` rust
let mut busy = Gpio::new()?.get(GPIO_BUSY)?.into_input_pullup();
busy.set_interrupt(gpio::Trigger::FallingEdge);

loop {
    start_conversion();
    busy.poll_interrupt(false, None);
    ...
    read_data();
}
```

🤔 Am I doing this right or is this a bug?

**Comment by golemparts** [comment]
Thanks for the compliment! Glad to hear you found the cause of the issue.
