### ISSUE TITLE
Interrupt reading multiple same level edges clarification

### ISSUE THREAD

**Issue by sadilekivan** [golemparts/rppal#106]
For some time I'm trying to find the best way to capture edge level events on a logical signal pin. I have been trying multiple libraries in multiple languages and often there is this behavior. I run a thread to capture the events of me pressing a button and then print them. I get an output like this:

```
High
Low
High
Low
High
High
High
Low
High
Low
Low
High
Low
```

I thought it's some stuff wrong with the libraries, but now I'm wondering if this is correct. The button pressing can definitely make edges faster then the response time of the raspberry pi, but how does the interrupt figure there has been another High edge when there was no Low edge before that? My though is that the circuitry loses the information and I just happen to catch the next edge which was the same level. So can I just safely ignore the redundant edges? Or am I doing something wrong?

**Comment by golemparts** [comment]
I noticed this never received a proper response. Apologies for that. Closing this as this is currently being discussed in detail in #149.
