### ISSUE TITLE
Spi::transfer_segments seems to require both read and write buffers

### ISSUE THREAD

**Issue by llowrey** [golemparts/rppal#11]
I'm trying to interface a CC1101 radio via SPI on a RPi2 running rasbian stretch with kernel 4.14.50-v7+.

The interface protocol is to send a command byte while simultaneously receving a status byte, then, while CS is still asserted, read or write 1 or more bytes depending on the command.

When I do the following, my 'register' array is not modified.

```
let cmd_ts = TransferSegment::new(Some(&mut status), Some(&cmd));
let reg_ts = TransferSegment::new(Some(&mut register), None);
let segments = [cmd_ts, reg_ts];
spi.transfer_segments(&segments).unwrap();
```
Note, the second segment has a receive buffer but 'None' for the send buffer.

However, if I do this, add an array of zeros for the send buffer, it works.

```
let cmd_ts = TransferSegment::new(Some(&mut status), Some(&cmd));
let reg_ts = TransferSegment::new(Some(&mut register), Some(&[0; 1]));
let segments = [cmd_ts, reg_ts];
spi.transfer_segments(&segments).unwrap();
```
Interestingly, I *can* specify None for the 1st segment's receive buffer and it works. So, perhaps the issue is only with the send buffer.

**Comment by golemparts** [comment]
I've found the cause. When a new `TransferSegment` instance is constructed, both buffers are compared, and the smallest of the two lengths is used as the transfer length. However, it didn't differentiate between a 0-length write buffer and an omitted (None) write buffer, causing the transfer length to be set to 0 in both cases. That explains the behavior you're seeing. I'll have a fix in for the upcoming 0.8.0 release, which should be released today or tomorrow.
