### ISSUE TITLE
Reason for not supporting 10-bit i2c addressing

### ISSUE THREAD

**Issue by AntonOellerer** [golemparts/rppal#113]
Hey,
Just out of interest, what is the reason for not supporting 10-bit addressing in i2c communication?
I looked around for a bit, but did not discover anything specific.
Best regards
Anton Oellerer

**Comment by golemparts** [comment]
Hey Anton. When RPPAL's I2C module was initially developed, 10-bit addressing wasn't supported by the underlying Linux drivers on any of the Raspberry Pi models available at the time. I haven't checked if this has changed recently, but you should be able to call `set_addr_10bit`, and it'll check if the underlying driver supports this feature.
