### ISSUE TITLE
GPIO starts fluctating

### ISSUE THREAD

**Issue by thinkrapido** [golemparts/rppal#121]
Sorry for asking this question here, but I don't see any reason, why this happens.
Maybe it is an electronic issue.
Please help.

I have this programm here: https://github.com/rusticus-io/sound-player/blob/main/src/main.rs

I monitor my gpio with watch -n 1 raspi-gpio get 4

Before I start the program everything works fine, but after I start my program the gpio pin starts fluctuating and I receive a is_high unnecessarily, so this projects plays sounds on and on and not only after short-circuiting V3.3 with GPIO4.

After reattaching from power supply the PIN behaves as expected again.

**Comment by golemparts** [comment]
If you're not using a pullup or pulldown resistor, your input pin is likely floating and returning seemingly random results. I suggest enabling the Raspberry Pi's built-in pulldown resistor by changing `into_input()` into `into_input_pulldown()` and see if that helps resolve the issue.
