### ISSUE TITLE
Interrupt service routines for Timers?

### ISSUE THREAD

**Issue by superlou** [golemparts/rppal#123]
This might be well beyond the scope of this library, but I was wondering if there is a way to set interrupt service routines for Timer match events. Looking at the BCM2711 and BCM2835 datasheets, it looks like there are 4 system timers which can fire interrupts on match, but I'm not sure how to determine which ones the operating system is using. Is that something that could fall under the scope of this library, or should it be a separate project?

**Comment by golemparts** [comment]
Thanks for the suggestion! While i'm not against adding support for timer interrupts, this might be better suited as a separate project. One of the goals I have for RPPAL is easy peripheral access without needing superuser privileges. As far as I'm aware, the only registers we can access directly without those privileges are in the GPIO section. I'm only somewhat familiar with (user space) timer interrupt support in Linux. I imagine there are already other crates out there that offer support for those.

If you come across anything that would make these a better fit for RPPAL I'd love to hear it though and we can revisit this.
