### ISSUE TITLE
Banana Pi M5 support

### ISSUE THREAD

**Issue by Chris2m** [golemparts/rppal#128]
What would it take to make the library compatible with the [Banana Pi M5](https://wiki.banana-pi.org/Banana_Pi_BPI-M5#Android_2)? Looking for the GPIO functionality specifically. I understand I would likely have to implement the `DeviceInfo`. Willing to contribute but need pointers.

**Comment by golemparts** [comment]
Unfortunately the GPIO functionality would probably be incompatible. RPPAL accesses the GPIO registers on the Raspberry Pi directly through `/dev/gpiomem`. Considering the Banana Pi M5 uses a different SoC, it's possible they copied the same register layout for compatibility reasons, but unlikely.

First thing I'd check is if a `/dev/gpiomem` device even exists. If it does, comparing any technical documentation specific to the GPIO would be a good second step.

At some point we'll likely move away from using `/dev/gpiomem` in favor of `/dev/gpiochip` which would make it easier to support other SBCs. If I remember correctly, last time I dove into `gpiochip`, there were some issues that prevented me from completely switching over. I'll have to recheck those. Adding compatibility for the Banana Pi M5 would definitely be a lot easier after that switch.
