### ISSUE TITLE
Add an example of graceful shutdown when SIGINT (GPIO)

### ISSUE THREAD

**Issue by Eduardo-RFarias** [golemparts/rppal#144]
I’m new to Rust, and I’m really struggling to implement code that properly drops GPIO pins when Ctrl + C (SIGINT) is pressed. The documentation states that Rust doesn’t automatically call the drop method when a SIGINT signal is received. However, I would greatly appreciate an example of how to handle this situation.

**Comment by golemparts** [comment]
Welcome to Rust @Eduardo-RFarias 😁 . There's an example in the examples folder that shows you how to handle signals using the `simple-signals` crate. Check out [gpio_blinkled_signals.rs](https://github.com/golemparts/rppal/blob/master/examples/gpio_blinkled_signals.rs).

Hope that helps!
