### ISSUE TITLE
Check if /dev/serial0 points to the correct device on all Pis

### ISSUE THREAD

**Issue by golemparts** [golemparts/rppal#166]
By default, `Uart::new` uses `/dev/serial0` to find the correct UART device to use. On the Raspberry Pi 5, this points to `/dev/ttyAMA10` instead of `/dev/ttyAMA0`, which is the debug UART/console. We need to check if using this still makes sense on all Pi devices, or if we need to use a different default based on the Pi we're running on. Currently, calling `with_path` instead of `new` is a valid workaround.

Also update the documentation to reflect Pi 5-specific configuration options to configure UART.

Also see #165.

**Comment by Dygear** [comment]
Worth a mention that on the Raspberry Pi 5, I needed to put `dtoverlay=uart0-pi5` into my `/boot/firmware/config.txt` file (at the bottom, can be placed in the `[all]` section, but `[pi5]` is also acceptable, but doesn't exist by default). That is what enabled me to use the GPIO 14/15 pins when reaching into `/dev/ttyAMA0`. The configuration here is a little tricky as it's not very well documented on the Raspberry Pi foundation side. Everything is there, but they don't outright call it out when you go to the UART section of the manual for the Raspberry Pi 5.
