### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by jacobrosenthal** [golemparts/rppal#25]
I just saw your delay traits and made me think my recent Countdown trait would fit here

https://github.com/jacobrosenthal/rust-bitbang-wiegand/blob/timeout/examples/rppal-rfid.rs#L39

Im using it for a timeout in my nonblocking implementation of weigand
https://github.com/jacobrosenthal/rust-bitbang-wiegand/blob/timeout/src/lib.rs#L75-L77

Interested?

**Comment by golemparts** [comment]
Thanks for the offer! I haven't had time yet to add support for the Countdown trait myself, so incorporating your implementation would be great. Would you mind opening a PR and adding it to the existing `hal.rs`?
