### ISSUE TITLE
Reasoning why read requres &mut self

### ISSUE THREAD

**Issue by rumatoest** [golemparts/rppal#3]
I can not see from your code any necessity of using &mut in read and even write functions.
Ok it is undertandable that write have to be &mut

But why pin read function require &mut self

It makes code to work with your library to be more complicated, because in most cases I do not expect to have mutable readings plus Rust compiler force me to do attional stuff to make &mut usage safe.

Could you remove &mut from value getters on gpio?

**Comment by golemparts** [comment]
You're correct. It looks like several of the references to self don't have to be mutable. I won't be able to remove all of them, because functions like set_mode need to keep track of any changes, but I'll remove &mut where it's not needed.

Thanks for the suggestion!
