### ISSUE TITLE
[Question] UART baud rates

### ISSUE THREAD

**Issue by piegamesde** [golemparts/rppal#31]
According to [the documentation](https://docs.golemparts.com/rppal/0.11.2/rppal/uart/struct.Uart.html#method.set_baud_rate), only a limited set of baud rates are supported. Why is this so? I've never seen any other application/interface restrict the number in one way or another. And why is zero a valid baud rate?

**Comment by golemparts** [comment]
Thanks for the question. RPPAL uses the `termios` functions to set the baud rate. The [`cfsetospeed`](https://linux.die.net/man/3/cfsetospeed) function doesn't support custom baud rates. Custom baud rates are possible through `termios2` using `TCSETS2`, however that's not supported by the current version of the `libc` crate. A speed of 0 is used to terminate a connection.

**Comment by piegamesde** [comment]
Thanks.
