### ISSUE TITLE
use of deprecated `std::mem::uninitialized`

### ISSUE THREAD

**Issue by Majkl578** [golemparts/rppal#34]
[`std::mem::uninitialized()`](https://doc.rust-lang.org/std/mem/fn.uninitialized.html) used in [`init_array!()`](https://github.com/golemparts/rppal/blob/5eb0f1480b58e7ecd027bc58d12b4a7f23e8d4b4/src/macros.rs#L36) is deprecated as of Rust 1.38.0 and should be replaced by [`MaybeUninit<T>`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html).

The deprecation is explained as follows:
> The reason for deprecation is that the function basically cannot be used correctly: the Rust compiler assumes that values are properly initialized. As a consequence, calling e.g. mem::uninitialized::<bool>() causes immediate undefined behavior for returning a bool that is not definitely either true or false. Worse, truly uninitialized memory like what gets returned here is special in that the compiler knows that it does not have a fixed value. This makes it undefined behavior to have uninitialized data in a variable even if that variable has an integer type. (Notice that the rules around uninitialized integers are not finalized yet, but until they are, it is advisable to avoid them.)

**Comment by golemparts** [comment]
Thanks for opening this issue! Adding it to the list for the upcoming release.
