### ISSUE TITLE
Can not use embedded-hal features

### ISSUE THREAD

**Issue by rumatoest** [golemparts/rppal#37]
There is a possibility that this is not a bug and I'm just a dumb coder but right now I believe in opposite. 

I've implemented DHT sensor driver based on HAL and I want to test it on RPI via rppal.

But I've found that I'm not able to use HAL traits in my code. 
Looks like in your code all traits implementation for HAL are in non public module.

**Comment by Majkl578** [comment]
You need to opt-in for those using feature flags: https://github.com/golemparts/rppal#usage

**Comment by rumatoest** [comment]
Actually I've opted out all features I need, but still I've got an error
```
expected trait embedded_hal::digital::v1::InputPin, found struct `rppal::gpio::pin::InputPin`
```
