### ISSUE TITLE
when ::new() is called error "No such file or directory" sets

### ISSUE THREAD

**Issue by fmc5046** [golemparts/rppal#54]
Hi I'm seeing an issue where any time I call new() (in regards to registering a GPIO pin or I2C) I get the error "No such file or directory"  Im using the latest version of rrpal (0.11.3) and a Raspberry pi 2B.  Is this a known issue or am I missing files?  I dont think its the permissions issue since I'm not getting that error.

Thanks
Fred

**Comment by fmc5046** [comment]
My bad....it was a permissions thing no issues just me

**Comment by d3249** [comment]
Hi @fmc5046 

I'm facing the same issue, can you share your solution?
