### ISSUE TITLE
Add support for newer models

### ISSUE THREAD

**Issue by haku956** [golemparts/rppal#67]
Some new models have been released which are not supported yet by rppal:

> c03114 	4B 	1.4 	4GB 	Sony UK
> d03114 	4B 	1.4 	8GB 	Sony UK
> c03130 	Pi 400 	1.0 	4GB 	Sony UK

See https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

**Comment by golemparts** [comment]
Added to the master branch. All currently available models are now recognized. Additional changes might be needed to support any new peripherals. If needed, those will be included in the 0.12.0 release.
