### ISSUE TITLE
Replace GPIO sysfs interface for interrupts with GPIO character device

### ISSUE THREAD

**Issue by golemparts** [golemparts/rppal#8]
The GPIO sysfs interface (`/sys/class/gpio`) has been deprecated, with the relatively new GPIO character device (`/dev/gpiochipN`) interface offered as a replacement. Since GPIO sysfs is currently used for interrupts, a migration to the GPIO cdev interface needs to happen before GPIO sysfs is removed (after 2020).

As an added benefit, this is also a workaround for a bug in Fedora where GPIO sysfs doesn't properly handle interrupts.

**Comment by golemparts** [comment]
All of the existing interrupt methods now use the new GPIO character device interface. On Raspbian they're working as intended.

**Comment by KuabeM** [comment]
As well as on Fedora - thank you, great job!
